# -*- coding: utf-8 -*-
"""Read the NOE class chapter (Markdown converted from the rulebook PDF) into sections.

Shared by extract_classes.py and extract_professions.py. NOE lives in the private vault
(`Neuro 5e/Podrecznik/NOE/`, regenerated by `Podrecznik/tools/pdf2md.py`); override the
location with the NOE_DIR environment variable.
"""
import io
import os
import re

NOE = os.environ.get("NOE_DIR", r"c:\Git\Neuroshima\neuro5e\Neuro 5e\Podrecznik\NOE")
KLASY = os.path.join(NOE, "07 KLASY")

CLASS_FILES = {
    "brutal": "01 BRUTAL.md",
    "cwaniak": "02 CWANIAK.md",
    "spec": "03 SPEC.md",
    "twardziel": "04 TWARDZIEL.md",
    "zlodziej": "05 ZŁODZIEJ.md",
    "zwiadowca": "06 ZWIADOWCA.md",
}

HEADING = re.compile(r"^(#{1,6})\s+(.*)$")


def plain(line):
    """Markdown line -> plain text (tables flattened, markup dropped)."""
    s = line
    if re.match(r"^\|?\s*:?-{3,}", s):
        return ""
    s = s.replace("<br>", " ").replace("[!info]", " ")
    s = re.sub(r"^\s*>\s?", "", s)
    s = re.sub(r"^\s*-\s+", "• ", s)
    s = s.replace("\\*", "\x01").replace("*", "").replace("\x01", "*").replace("\\", "")
    s = s.replace("|", " ")
    return re.sub(r"\s+", " ", s).strip()


def read_sections(path):
    """[(level, title, [plain body lines])] in file order; level 0 = text before any heading."""
    out = [(0, "", [])]
    for line in io.open(path, encoding="utf-8").read().split("\n---\n", 1)[-1].splitlines():
        if line.startswith("<!--"):
            continue
        m = HEADING.match(line)
        if m:
            out.append((len(m.group(1)), m.group(2).strip(), []))
            continue
        p = plain(line)
        if p:
            out[-1][2].append(p)
    return out


def split_action(title):
    """'POZIOM 2: Z BARA! [B]' -> ('POZIOM 2: Z BARA!', 'B')."""
    m = re.match(r"^(.*?)\s*\[([ABRIL])\]\s*:?$", title)
    if m:
        return m.group(1).strip(), m.group(2)
    return title.rstrip(":").strip(), None
